using System;
using System.Threading;
using System.Threading.Tasks.Dataflow;
public class Test
{
    public static void Main()
    {
        try
        {
            Console.Write($"Enter num1:");
            int num1 = Convert.ToInt32(Console.ReadLine());
            Console.Write($"Enter num2:");
            int num2 = Convert.ToInt32(Console.ReadLine());
            
            //custom exeption created
            if(num2>num1)
            {
                throw new ArgumentException("num2 cannot be greater than num1");//argument exception
            }

            int result = num1 / num2;
            Console.WriteLine($"{result}");

        }

      //Exeption list(overflow,format and dividedByZero exeption etc.)
        catch (OverflowException)
        {
            Console.WriteLine($"Exception:the number is too big.");
        }

         catch(DivideByZeroException)
      {
       Console.WriteLine($"Exception:you cannot divide by zero.");     
      }

      catch(FormatException e)
      {
        Console.WriteLine($"Exception:{e.Message}");
        
      }
       
     //This is for all kind of exception.
        catch (Exception e)
        {
            Console.WriteLine($"Exception:{e.Message}");//custom exception output
        }

     //Here are those code which will always work
        finally
        {
            Console.WriteLine($"good bye");
        }


    }
}